// isci trimmer/stripper for clipboard
//  Inspired by: http://mrbool.com/manipulating-clipboard-content-with-java/24758

import java.awt.Toolkit; 
import java.awt.datatransfer.DataFlavor; 
import java.awt.datatransfer.StringSelection; 
import java.awt.datatransfer.Transferable; 


public class IsciTrimmer { public static void main(String args[]) {

}

// yeah you can get this to run on a thread in the background perpetually trying to strip contents of clipboard to acceptable
// parameters
